### ISSUE TITLE
Coin Struct Missing Fields

### ISSUE THREAD

**Issue by PrettyBoyHelios** [grupokindynos/obol#10]
**Is your feature request related to a problem? Please describe.**
I'm currently using coinfactory and coin models for Adrestia. As a way of reusing tested code and avoiding high code modification in the future. Eros requested a common model repository, and I know I should wait for that, but I think this modifications could help. They would be for the [Coin struct](https://github.com/grupokindynos/obol/blob/e611fc9eaacfe0354fa66e8ebd047e89eac05746/models/coin-factory/coins.go#L104).

## Solution Proposal
I would like to add this fields as they represent configuration values for each coin and centralizing coin configs in a single file could prove useful.
![image](https://user-images.githubusercontent.com/40777080/65261791-a18cfb00-dace-11e9-8546-892b299fa576.png)

I see the network object is rather complicated and of not mush use.

## Additional Contest
I don't know if it can be fixed in the obol models or in a new common repo. Either way I'm waiting for either completition or assignation of the task.

**Comment by eabz** [comment]
@PrettyBoyHelios Current common coin-factory is done, please submit a PR to https://github.com/grupokindynos/common/tree/master/coin-factory
