### ISSUE TITLE
Missing DGB rates

### ISSUE THREAD

**Issue by PrettyBoyHelios** [grupokindynos/obol#9]
### Describe the issue
Rates for DGB are not found.

**Example:**

Explain the workaround that you used to properly replicate the issue.

### Expected behaviour

Return DGB rates for all 3 endpoints.

### Actual behaviour
<img width="1392" alt="Screen Shot 2019-09-18 at 11 28 18 AM" src="https://user-images.githubusercontent.com/40777080/65167124-98852680-da07-11e9-98d4-86041b1ad200.png">
<img width="1392" alt="Screen Shot 2019-09-18 at 11 28 25 AM" src="https://user-images.githubusercontent.com/40777080/65167125-98852680-da07-11e9-85a3-6b96bd1c7d45.png">

![image](https://user-images.githubusercontent.com/40777080/65167203-b783b880-da07-11e9-8d93-b0a37d97fadb.png)

**Comment by eabz** [comment]
I don't know what was the issue, but DGB rates are working correctly for me: http://obol.polispay.com/simple/dgb

**Comment by PrettyBoyHelios** [comment]
I guess it was an external error. Closing.
